apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-pod
    image: alpine
    command: ["sleep", "infinity"]

# apk update ; apk add lftp;
# echo "set ssl:verify-certificate no" > /root/.lftprc


