apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana # as deployment what manage_
  template:
    metadata:
      labels:
        app: grafana ###
    spec:
      containers:
      - name: grafana
        image: grafana_images_koto
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/livenessprobe.sh"]
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip : production-public-ips
spec:
  selector:
    app: grafana ###
  type: LoadBalancer
  # loadBalancerIP: 192.168.49.2
  ports:
  - protocol: TCP
    name: grafana
    port: 3000
    targetPort: 3000
    nodePort: 3000