apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # any name??
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_images_koto
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/livenessprobe.sh"]
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip : production-public-ips
spec:
  selector:
    app: nginx
  type: LoadBalancer
  # loadBalancerIP: 192.168.49.2
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80