apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin # as deployment what manage_
  template:
    metadata:
      labels:
        app: phpmyadmin ###
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_images_koto
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  selector:
    app: phpmyadmin ###
  type: LoadBalancer
  # loadBalancerIP: 192.168.49.2
  ports:
  - protocol: TCP
    name: phpmyadmin
    port: 5000
    targetPort: 5000
    nodePort: 5000


# annotations 
# metal